Test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,14 @@ jobs:
 
       - name: Run psalm
         run: |
-          exit_code=$(docker-compose -f docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev ./scripts/analysis/psalm.sh; echo \$?")
+          exit_code=$(docker-compose -f docker-compose.yml -p buildadoc-dev exec -T buildadoc-dev sh "./scripts/analysis/psalm.sh; echo \$?")
+          echo "Psalm analysis exit code: $exit_code"
+          if [ "$exit_code" -eq 0 ]; then
+            echo "Psalm analysis successful"
+          else
+            echo "Psalm analysis failed with exit code $exit_code"
+            exit $exit_code
+          fi
 
       - name: Run cs-fixer
         run: |
