Test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,17 +28,20 @@ jobs:
       - name: Run psalm
         run: |
           docker-compose -f docker-compose.yml -p buildadoc-dev exec -it buildadoc-dev ./scripts/analysis/psalm.sh --abort-on-container-exit
-          exit_code=$?
-          echo "::set-output name=exit_code::$exit_code"
+          echo "::set-output name=exit_code::$?"
 
       - name: Check Exit Code
         run: |
-          echo ${exit_code}
-          if [ "${{ steps.execute_docker_compose.outputs.exit_code }}" -eq 0 ]; then
+          exit_code="${{ steps.run_docker_compose.outputs.exit_code }}"
+          if [ -z "$exit_code" ]; then
+            echo "Exit code not available"
+            exit 1
+          fi
+          if [ "$exit_code" -eq 0 ]; then
             echo "Script executed successfully"
           else
-            echo "Script failed with exit code ${{ steps.execute_docker_compose.outputs.exit_code }}"
-            exit ${{ steps.execute_docker_compose.outputs.exit_code }}
+            echo "Script failed with exit code $exit_code"
+            exit $exit_code
           fi 
 
       - name: Run cs-fixer
